# Generated by Django 4.1.7 on 2023-07-06 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_student_teachers_alter_student_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
    ]
