# Generated by Django 4.2.3 on 2023-07-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='date_and_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время измерения'),
        ),
    ]
