# Generated by Django 4.2.3 on 2023-07-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0005_alter_measurement_sensor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
